/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_gaohaohao_jnidemo_HelloJNI */

#ifndef _Included_cn_gaohaohao_jnidemo_HelloJNI
#define _Included_cn_gaohaohao_jnidemo_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_gaohaohao_jnidemo_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_gaohaohao_jnidemo_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
