spring:
  application:
    name: service-zuul
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name} # 服务调用的名字
        health-check-interval: 15s
server:
  port: 8506

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

zuul:
  routes:
    api:
      path: /**
      serviceId: my-first-consul-service