spring:
  application:
    name: hystrix-service
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: hystrix-service # 服务调用的名字
        health-check-interval: 15s
server:
  port: 8505